# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.SmallIntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.SmallIntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
